### ISSUE TITLE
Make the manager modal default to "upcoming"

### ISSUE THREAD

**Issue by abea** [apostrophecms/apostrophe-events#36]
Right now the manager modal defaults to show all events, whether upcoming or past. I'd suggest changing this to default to showing upcoming events with the idea that those are the ones that will most likely need acting on. Easier for the end user to get to the stuff they need to work on that way.

I can do the code update but wanted to run the idea by folks first.

CC @carlykaras @boutell

**Comment by carlykaras** [comment]
UX approves!

**Comment by boutell** [comment]
Makes sense to me.
